#OPERADORES MATEMATICOS

print(10+5) #Suma
print(10-5) #Resta   
print(10*5) #Multiplicacion
print(10/4) #Division

#DIVICION ENTERA 
print(10//4) #Division entera

#MODULO
print(10%3) #Modulo o residuo de la division

#EXPONENTE
print(2**4) #2 elevado a la 4

#ADICIONAR 

X = 10
X = X + 5       #X = X + 5
print(X)

y = 10
y += y + 5          #y = y + 5
print(y)

#PRECEDENCIA DE LOS OPERADORES

x = 10 + 3 * 2
print(x) #El resultado es 16, porque la multiplicacion se realiza antes que la suma
